
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/smartcart_ecommerce
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Distributed Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Zipkin Configuration
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Logging Pattern
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]
